### ISSUE TITLE
Reborn shouts: Something is wrong!

### ISSUE THREAD

**Issue by schellenberg** [aroberge/reeborg-dist#1]
After unzipping the repository, and then moving it onto a basic webhost, I get the following error:
"Reeborg shouts: Something is wrong!" when I attempt to simply move() in the built-in Alone world.

![screen shot 2017-08-31 at 7 11 17 pm](https://user-images.githubusercontent.com/227656/29951507-59e940e8-8e80-11e7-8310-4f17033be826.png)

The instance in question is currently hosted at:
http://wmcicompsci.ca/reeborg/reeborg.html

**Comment by aroberge** [comment]
When I look at the console, I see that it cannot load a python script.  What kind of server are you using?
In my case, I know that I had to have
</FilesMatch> RemoveHandler .py
in my .htaccess as mentioned on https://github.com/aroberge/reeborg-dist

**Comment by aroberge** [comment]
(EDIT) My .htaccess file (for an Apache server) includes the following:

    # cache for 6 hours
    <FilesMatch ".(js|css|html|htm)$">
    Header set Cache-Control "max-age=21600"
    </FilesMatch>
    RemoveHandler .py

with the last line being the relevant one: this prevents the server to interpret Python files, and lets Brython upload them using ajax.

Your server appears to be nginx and not apache ... I do not know what the equivalent configuration would be.

**Comment by schellenberg** [comment]
Setting the Apache handler was the issue. Thanks for the quick help!
